"""Shared orchestrator HTTP client for the MCP tools.

``runs.py`` and ``cache.py`` each carried their own header helper — one named
``_orchestrator_headers``, the other ``_headers`` — doing identical work. One
client, one name.
"""

from __future__ import annotations

import re

from shared.http_client import BaseHttpClient

from ..config import settings


def orchestrator_client() -> BaseHttpClient:
    return BaseHttpClient(
        settings.ORCHESTRATOR_URL,
        api_key=settings.ORCHESTRATOR_API_KEY,
        timeout=settings.HTTP_TIMEOUT,
    )


#: Run ids are generated by `make_run_id`: experiment/ticker/model/timestamp
#: joined by "__", with "/" replaced. Nothing else is a valid id.
_RUN_ID_RE = re.compile(r"^[A-Za-z0-9._\-]+$")


def validate_run_id(run_id: str) -> str:
    """Reject a run id that could alter the request path.

    These ids reach the MCP from an agent acting on prompt-injectable content.
    httpx resolves dot segments and preserves a query string, so an unchecked
    ``run_id`` of ``x/../../cache?older_than_seconds=1`` turns a `delete_run`
    call into a bulk cache purge — a destructive outcome the tool name does not
    imply, even though no privilege boundary is crossed.
    """
    if not run_id or not _RUN_ID_RE.match(run_id):
        raise ValueError(
            f"invalid run_id {run_id!r}: expected only letters, digits, '.', '_' and '-'"
        )
    return run_id
